function sm_boom_lift_crawler_plot12motionseq(motion)
% Code to plot motion sequence from sm_boom_lift_crawler
%% Plot Description:
%

% Copyright 2020 The MathWorks, Inc.

%% Plot results
% Reuse figure if it exists, else create new figure
figString = 'h12_sm_boom_lift_crawler_valves';
% Only create a figure if no figure exists
figExist = 0;
fig_hExist = evalin('base',['exist(''' figString ''')']);
if (fig_hExist)
    figExist = evalin('base',['ishandle(' figString ') && strcmp(get(' figString ', ''type''), ''figure'')']);
end
if ~figExist
    fig_h = figure('Name',figString);
    assignin('base',figString,fig_h);
else
    fig_h = evalin('base',figString);
end
figure(fig_h)
clf(fig_h)
scale_factor = 0.45;
% Sky valves
plot(0,0); % Placeholder for colors
hold on
plot(motion.basketR.t,...
    (motion.basketR.q-motion.basketR.q(1))/...
    max(abs(motion.basketR.q)+eps)*scale_factor+10.5, 'LineWidth', 1);
plot(motion.jib.t,...
    (motion.jib.p-motion.jib.p(1))/...
    max(abs(motion.jib.p)+eps)*scale_factor+9.5, 'LineWidth', 1);
plot(motion.extend.t,...
    (motion.extend.p-motion.extend.p(1))/...
    max(abs(motion.extend.p)+eps)*scale_factor+8.5, 'LineWidth', 1);
plot(motion.tilt.t,...
    (motion.tilt.p-motion.tilt.p(1))/...
    max(abs(motion.tilt.p)+eps)*scale_factor+7.5, 'LineWidth', 1);
plot(motion.lift.t,...
    (motion.lift.p-motion.lift.p(1))/...
    max(abs(motion.lift.p)+eps)*scale_factor+6.5, 'LineWidth', 1);
plot(motion.turret.t,...
    (motion.turret.q-motion.turret.q(1))/...
    max(abs(motion.turret.q)+eps)*scale_factor+5.5, 'LineWidth', 1);
plot(0,0); % Placeholder for colors
plot(0,0); % Placeholder for colors
plot(0,0); % Placeholder for colors
plot(motion.outFL.t,...
    (motion.outFL.p-motion.outFL.p(1))/...
    max(abs(motion.outFL.p)-motion.outFL.p(1)+eps)*scale_factor+1.5, 'LineWidth', 1);
plot(motion.TrackL.t,...
    (motion.TrackL.p-motion.TrackL.p(1))/...
    max(abs(motion.TrackL.p)+eps)*scale_factor+0.5, 'LineWidth', 1);
hold off

set(gca,'YLim',[0 12])
set(gca,'YTick',[0.5:1:11.5])
set(gca,'YTickLabel',{...
    'Track',...
    'Outrigger',...
    ' ',...
    ' ',...
    ' ',... 
    'Turret',...
    'Lift',...
    'Tilt',...
    'Extend',...
    'Jib',...
    'BasketR',...
    ' '})
xlabel('Time (s)');
title(['Motion Sequence: ' motion.name])

% Remove temporary variables
clear simlog_handles
